services:
  nginx:
    image: nginx
    ports:
      - "8181:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/nginx.conf:/nginx.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php:php
    command: nginx -c /nginx.conf

  php:
    build: ./php/
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/conf.d/php.ini:/usr/local/etc/php/php.ini
